# Generated by Django 3.0.4 on 2020-04-04 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventTitle', models.CharField(max_length=30)),
                ('catergory', models.CharField(max_length=30)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('description', models.TextField()),
                ('priorityLevel', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleTitle', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=30)),
                ('site', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timetable.Event')),
                ('eventType', models.CharField(max_length=30)),
            ],
            bases=('timetable.event',),
        ),
        migrations.CreateModel(
            name='ExtraCurricularEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timetable.Event')),
                ('coordinator', models.CharField(max_length=30)),
                ('streetName', models.CharField(max_length=30)),
                ('postcode', models.CharField(max_length=30)),
                ('capacity', models.CharField(max_length=4)),
                ('contactEmail', models.EmailField(max_length=254)),
                ('bookingRequired', models.BooleanField()),
                ('restriction', models.CharField(max_length=4)),
            ],
            bases=('timetable.event',),
        ),
        migrations.CreateModel(
            name='FriendsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_friend', models.ManyToManyField(to='timetable.Account')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='roomID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Room'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseTitle', models.CharField(max_length=30)),
                ('module', models.ManyToManyField(to='timetable.Module')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='eventID',
            field=models.ManyToManyField(to='timetable.Event'),
        ),
        migrations.AddField(
            model_name='account',
            name='roomID',
            field=models.ManyToManyField(to='timetable.Room'),
        ),
        migrations.CreateModel(
            name='StudentAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timetable.Account')),
                ('studyLevel', models.CharField(max_length=1)),
                ('coursePrograme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Course')),
            ],
            bases=('timetable.account',),
        ),
    ]
