# Generated by Django 3.0.4 on 2020-04-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='universityID',
            field=models.CharField(default='xxxx', max_length=10),
        ),
        migrations.AddField(
            model_name='module',
            name='moduleCode',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
